// export const NATIONALITIES = {
//   AU: { nat: 'Australian', color: 'red' },
//   BR: 'Brazilian',
//   CA: 'Canadian',
//   CH: 'Chiness',
//   DE: 'German',
//   DK: 'Danish',
//   ES: 'Estonian',
//   FI: 'Finnish',
//   FR: 'French',
//   GB: 'British',
//   IE: 'Irish',
//   IR: 'Iranian',
//   NO: 'Norwegian',
//   NL: 'Dutch',
//   NZ: 'New Zelander',
//   TR: 'Turkish',
//   US: 'American',
// };

export const NATIONALITIES = {
  AU: { nat: 'Australian', color: 'white', bgcolor: '#F98866' },
  BR: { nat: 'Brazilian', color: 'white', bgcolor: '#FF420E' },
  CA: { nat: 'Canadian', color: 'white', bgcolor: '#80BD9E' },
  CH: { nat: 'Chiness', color: '#444444', bgcolor: '#cfd8dc' },
  DE: { nat: 'German', color: 'white', bgcolor: '#8d6e63' },
  DK: { nat: 'Danish', color: 'MediumBlue', bgcolor: 'LightCyan' },
  ES: { nat: 'Estonian', color: '#4a148c', bgcolor: '#e1bee7' },
  FI: { nat: 'Finnish', color: '#880e4f', bgcolor: '#f48fb1' },
  FR: { nat: 'French', color: '#b71c1c', bgcolor: '#ffcdd2' },
  GB: { nat: 'British', color: '#0d47a1', bgcolor: '#bbdefb' },
  IE: { nat: 'Irish', color: '#311b92', bgcolor: '#d1c4e9' },
  IR: { nat: 'Iranian', color: '#d1c4e9', bgcolor: '#311b92' },
  NO: { nat: 'Norwegian', color: '#e1f5fe', bgcolor: '#0277bd' },
  NL: { nat: 'Dutch', color: '#e0f7fa', bgcolor: '#006064' },
  NZ: { nat: 'Zelander', color: '#004d40', bgcolor: '#b2dfdb' },
  TR: { nat: 'Turkish', color: '#f1f8e9', bgcolor: '#33691e' },
  US: { nat: 'American', color: '#fff3e0', bgcolor: '#ef6c00' },
};
